/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define BIGREQS 1

#define BUILDERADDR "cygwin@cygwin.com"

#define BUILDERSTRING "Package: version 21.1.12-1 built 2024-12-22"

#define BUSFAULT 1

#define COMPILEDDEFAULTFONTPATH "catalogue:/etc/X11/fontpath.d,built-ins"

#define COMPOSITE 1

#undef CONFIG_HAL

#undef CONFIG_UDEV

#undef CONFIG_UDEV_KMS

#undef CONFIG_WSCONS

#undef CSRG_BASED

#define DAMAGE 1

#define DBE 1

#define DDXBEFORERESET 1

#define DDXOSVERRORF 1

#undef DEBUG

#define DGA 1

#define DPMSExtension 1

#undef DRI2

#undef DRI3

#define DRI_DRIVER_PATH "/usr/lib/dri"

#undef GBM_BO_WITH_MODIFIERS

#undef GLAMOR

#undef GLAMOR_HAS_EGL_QUERY_DMABUF

#undef GLAMOR_HAS_EGL_QUERY_DRIVER

#undef GLAMOR_HAS_GBM

#undef GLAMOR_HAS_GBM_LINEAR

#define GLXEXT 1

#define HASXDMAUTH 1

#undef HAS_APERTURE_DRV

#define HAS_SHM 1

#undef HAVE_ACPI

#undef HAVE_APM

#define HAVE_ARC4RANDOM_BUF 1

#undef HAVE_BACKTRACE

#define HAVE_CBRT 1

#undef HAVE_DBUS

#define HAVE_DLFCN_H 1

#undef HAVE_EPOLL_CREATE1

#undef HAVE_EXECINFO_H

#define HAVE_FCNTL_H 1

#define HAVE_FNMATCH_H 1

#define HAVE_GETEUID 1

#define HAVE_GETIFADDRS 1

#define HAVE_GETPEEREID 1

#undef HAVE_GETPEERUCRED

#define HAVE_GETPROGNAME 1

#define HAVE_GETUID 1

#undef HAVE_GETZONEID

#undef HAVE_ISASTREAM

#define HAVE_ISSETUGID 1

#undef HAVE_LIBBSD

#undef HAVE_LIBUNWIND

#undef HAVE_LINUX_AGPGART_H

#undef HAVE_MEMFD_CREATE

#define HAVE_MKOSTEMP 1

#define HAVE_MMAP 1

#define HAVE_POLL 1

#undef HAVE_POLLSET_CREATE

#undef HAVE_PORT_CREATE

#define HAVE_POSIX_FALLOCATE 1

#define HAVE_PTHREAD_SETNAME_NP_WITH_TID 1

#define HAVE_REALLOCARRAY 1

#define HAVE_SETEUID 1

#define HAVE_SETITIMER 1

/* Use CryptoAPI SHA1 functions */
#define HAVE_SHA1_IN_CRYPTOAPI 1

#undef HAVE_SHMCTL64

#define HAVE_SIGACTION 1

#define HAVE_SIGPROCMASK 1

#define HAVE_STDLIB_H 1

#define HAVE_STRCASECMP 1

#define HAVE_STRCASESTR 1

#define HAVE_STRINGS_H 1

#define HAVE_STRING_H 1

#define HAVE_STRLCAT 1

#define HAVE_STRLCPY 1

#define HAVE_STRNCASECMP 1

#define HAVE_STRNDUP 1

#undef HAVE_SYSTEMD_DAEMON

#undef HAVE_SYS_AGPGART_H

#undef HAVE_SYS_AGPIO_H

#define HAVE_SYS_SYSMACROS_H 1

#define HAVE_SYS_UN_H 1

#define HAVE_SYS_UTSNAME_H 1

#define HAVE_TIMINGSAFE_MEMCMP 1

#define HAVE_TYPEOF 1

#define HAVE_UNISTD_H 1

#define HAVE_VASPRINTF 1

#define HAVE_VSNPRINTF 1

#undef HAVE_WALKCONTEXT

#undef HAVE_XSHMFENCE

#define INPUTTHREAD 1

#define IPv6 1

#define LISTEN_LOCAL

#define LISTEN_TCP

#undef LISTEN_UNIX

#define MITSHM 1

#define MONOTONIC_CLOCK 1

#undef NEED_DBUS

#define PANORAMIX 1

#undef PCCONS_SUPPORT

#undef PCVT_SUPPORT

#define PRESENT 1

#define PROJECTROOT "/usr"

#define RANDR 1

#define RENDER 1

#define RES 1

#define SCREENSAVER 1

#define SECURE_RPC 1

#define SERVER_MISC_CONFIG_PATH "/usr/lib/xorg"

#define SHAPE 1

#define SUID_WRAPPER_DIR "/usr/libexec"

#undef SVR4

#define SYSCONFDIR "/etc"

#undef SYSCONS_SUPPORT

#undef SYSTEMD_LOGIND

#define TCPCONN 1

#define UNIXCONN 1

#undef WITH_LIBDRM

#undef WITH_VGAHW

#undef WSCONS_SUPPORT

#define XACE 1

#define XCMISC 1

#define XCONFIGFILE "xorg.conf"

#undef XCSECURITY

#define XDMCP 1

#define XF86BIGFONT 1

#undef XF86DRI

#define XF86VIDMODE 1

#define XFIXES 1

#define XFreeXDGA 1

#define XINERAMA 1

#define XINPUT 1

#define XKB_DFLT_RULES "base"

#define XORGSERVER 1

#define XORG_VERSION_CURRENT 12101012

#define XRECORD 1

#undef XSELINUX

#undef XSERVER_DTRACE

#undef XSERVER_LIBPCIACCESS

#undef XSERVER_PLATFORM_BUS

#define XSYNC 1

#define XTEST 1

#define XTRANS_SEND_FDS 1

#undef XV

#define XVENDORNAME "The Cygwin/X Project"

//#define XVENDORNAMESHORT "Cygwin/X"
#define XVENDORNAMESHORT "wsl/X"

#define X_BYTE_ORDER X_LITTLE_ENDIAN

#undef XvExtension

#undef XvMCExtension

#define _DIX_CONFIG_H_ 1

#define _GNU_SOURCE 1

#define _XITYPEDEF_POINTER 1

#define _XSERVER64 1

#define _XTYPEDEF_POINTER 1

#define __VENDORDWEBSUPPORT__ "https://x.cygwin.com/"

#define __XSERVERNAME__ "Xorg"

