/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define VENDOR_MAN_VERSION "Version 21.1.12"

#define VENDOR_NAME "The Cygwin/X Project"

//#define VENDOR_NAME_SHORT "Cygwin/X"
#define VENDOR_NAME_SHORT "wsl/X"

#define VENDOR_RELEASE 12101012

#define VENDOR_WEB "https://x.cygwin.com/"

